version: '3'
services:
  pricer:
    image: "quay.io/uar_openshift/tradezero-pricer:latest"
    depends_on:
      - mongo-1
    links:
      - mongo-1
    restart: always
    hostname: tradezero-pricer-1
    environment:
      WORDPRESS_DB_HOST: mongo
      WORDPRESS_DB_USER: tradezero
      WORDPRESS_DB_PASSWORD: verysecret
      WORDPRESS_DB_NAME: tradezero-pricer
    ports:
      - "8080:8080"
  mongo:
    image: "docker.io/library/mongo:latest"
    hostname: mongo-1
    restart: always
    environment:
        MONGO_INITDB_DATABASE: tradezero-pricer
        MONGO_INITDB_ROOT_USERNAME: tradezero
        MONGO_INITDB_ROOT_PASSWORD: verysecret

