version: '3'
services:
  pricer:
    image: "quay.io/uar_openshift/tradezero-pricer:0.1.5"
    depends_on:
      - mongo
    links:
      - mongo
    restart: always
    hostname: tradezero-pricer-1
    environment:
      TZP_DB_HOST: mongo
      TZP_DB_USERNAME: tradezero
      TZP_DB_PASSWORD: verysecret
      TZP_DB_NAME: tradezero-pricer
    ports:
      - "8080:8080"
  mongo:
    image: "docker.io/library/mongo:latest"
    hostname: mongo-1
    restart: always
    environment:
        MONGO_INITDB_DATABASE: tradezero-pricer
        MONGO_INITDB_ROOT_USERNAME: tradezero
        MONGO_INITDB_ROOT_PASSWORD: verysecret
    ports:
      - "27017:27017"
    volumes:
      - mongodbvol:/data/db
volumes:
  mongodbvol:
  
